project:
  type: website
  output-dir: docs

website:
  title: "Deepthi Dayanand"
  navbar:
    right:
      # - href: index.qmd
      # text: Home
      # - about.qmd
      
      - projects.qmd
      - text: Resume
        href: Resume_DeepthiDayanand.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

